### PR TITLE
Add support for mpt3sas cards

### PR DESCRIPTION
**Pull request by jcpunk**
This should add some limited support for mpt3sas cards.

Additionally unsupported features are now silently ignored rather than making an attempt to set them each time.

### CODE REVIEW

**Comment by jcpunk** [comment]
@johnwarburton Figured I'd run this past you before putting it in...

**Comment by johnwarburton** [comment]
Thanks @jcpunk for including me

I ran the new code on a test box, and its no longer working for me. In this case I should have it turn of patrol reads
```
# facter --custom-dir puppet-modules-pr12/storcli/lib/facter/ megaraid | grep 'PR Mode'
        PR Mode => "Auto",

# puppet apply --config ./puppet.conf --modulepath=/export/home/jwarburt/puppet-modules-pr12 -e "include storcli" --verbose --test
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Caching facts for hostname.example.com
Info: 'replace_facts' command for hostname.example.com submitted to PuppetDB with UUID a69e6bed-f066-4d60-98da-9d3f6c2bdf77
Notice: Compiled catalog for hostname.example.com in environment prod in 0.12 seconds
Info: Caching catalog for hostname.example.com
Info: 'replace_catalog' command for hostname.example.com submitted to PuppetDB with UUID 054b9d23-8d65-4e7d-9f2c-53ffe3c98e4f
Info: Using environment 'prod'
Info: Applying configuration version '1660279416'
Notice: Applied catalog in 0.39 seconds
```
Running the above with `—debug` shows
```
Debug: Exec[Disable patrolread on MegaRAID controller /c0](provider=shell): Executing check '["/bin/sh", "-c", "/usr/local/sbin/perccli64 /c0 show patrolRead | grep 'PR Mode' | grep Disable"]'
Debug: Executing: '/bin/sh -c /usr/local/sbin/perccli64 /c0 show patrolRead | grep 'PR Mode' | grep Disable'
Debug: Exec[Disable patrolread on MegaRAID controller /c0](provider=shell): Executing check '["/bin/sh", "-c", "/usr/local/sbin/perccli64 /c0 show patrolRead | grep 'Status = Success'"]'
Debug: Executing: '/bin/sh -c /usr/local/sbin/perccli64 /c0 show patrolRead | grep 'Status = Success''
Debug: /Stage[main]/Storcli::Configure/Exec[Disable patrolread on MegaRAID controller /c0]/unless: Status = Success
Debug: /Stage[main]/Storcli::Configure/Exec[Disable patrolread on MegaRAID controller /c0]: '/usr/local/sbin/perccli64 /c0 set patrolread=off' won't be executed because of failed check 'unless'
```

Running the current code in debug shows it turning off patrol reads
```
Debug: Exec[Disable patrolread on MegaRAID controller /c0](provider=shell): Executing check '["/bin/sh", "-c", "/usr/local/sbin/perccli64 /c0 show patrolRead | grep 'PR Mode' | grep Disable"]'
Debug: Executing: '/bin/sh -c /usr/local/sbin/perccli64 /c0 show patrolRead | grep 'PR Mode' | grep Disable'
Debug: Exec[Disable patrolread on MegaRAID controller /c0](provider=shell): Executing '["/bin/sh", "-c", "/usr/local/sbin/perccli64 /c0 set patrolread=off"]'
Debug: Executing: '/bin/sh -c /usr/local/sbin/perccli64 /c0 set patrolread=off'
Notice: /Stage[main]/Storcli::Configure/Exec[Disable patrolread on MegaRAID controller /c0]/returns: executed successfully
Debug: /Stage[main]/Storcli::Configure/Exec[Disable patrolread on MegaRAID controller /c0]: The container Class[Storcli::Configure] will propagate my refresh event

# facter --custom-dir puppet-modules-pr12/storcli/lib/facter/ megaraid | grep 'PR Mode'
        PR Mode => "Disable",
```

I have not seen the idiom of using an array for `unless` to test, so I am not sure if it is supposed to `AND` or `OR` the elements in it

**Comment by jcpunk** [comment]
My reading of https://puppet.com/docs/puppet/7/types/exec.html#exec-attribute-unless indicates the `unless` checks must all pass.

Can I get the output of `/usr/local/sbin/perccli64 /c0 show patrolRead`?

**Comment by johnwarburton** [comment]
My reading of https://puppet.com/docs/puppet/7/types/exec.html#exec-attribute-unless indicates the `unless` would only run if *every* command in the array has a non-zero exit code

The output of `usr/local/sbin/perccli64 /c0 show patrolRead` is
```
# /usr/local/sbin/perccli64 /c0 show patrolRead
Controller = 0
Status = Success
Description = None


Controller Properties :
=====================

---------------------------------------------
Ctrl_Prop               Value
---------------------------------------------
PR Mode                 Auto
PR Execution Delay      168 hours
PR iterations completed 35
PR Next Start time      08/13/2022, 03:00:00
PR on SSD               Disabled
PR Current State        Active 0
PR Excluded VDs         None
---------------------------------------------
```

So the two commands being run are:
```
# /usr/local/sbin/perccli64 /c0 show patrolRead | grep 'PR Mode' | grep Disable; echo $?
1
# /usr/local/sbin/perccli64 /c0 show patrolRead | grep 'Status = Success'; echo $?
Status = Success
0
```
Not every command here has a non zero exit code which is why the code is not being triggered

**Comment by jcpunk** [comment]
I've tried to rework the logic, does this work better now?

**Comment by johnwarburton** [comment]
That's great - logic looks good. Thanks!

```
# puppet apply --config ./puppet.conf --modulepath=/export/home/jwarburt/puppet-modules-pr12/ -e "include storcli" --verbose --test --noop
Info: Loading facts
...
Info: Using environment 'prod'
Info: Applying configuration version '1660801941'
Notice: /Stage[main]/Storcli::Configure/Exec[Disable patrolread on MegaRAID controller /c0]/returns: current_value 'notrun', should be ['0'] (noop)
Notice: Class[Storcli::Configure]: Would have triggered 'refresh' from 1 event
Notice: Class[Storcli]: Would have triggered 'refresh' from 1 event
Notice: Stage[main]: Would have triggered 'refresh' from 2 events
Notice: Applied catalog in 0.41 seconds
```

**Pull request merged**
